### ISSUE TITLE
Fails in gatsby on bundle generation

### ISSUE THREAD

**Issue by will-t-harris** [luchoster/react-ig#2]
Tried running your package on a gatsby site using the username prop, got the following errors:

![image](https://user-images.githubusercontent.com/8484245/83715600-a1904500-a5e2-11ea-92aa-3179e062154e.png)

Not sure if some dependencies are missing from the npm package, or what else might be going on. Have you run into this before?

**Comment by luchoster** [comment]
I think I was missing a dependency for the typography. But I fixed it. Please update to the latest version and it should be fine.

**Comment by will-t-harris** [comment]
That did resolve the issue I was having, I can run `gatsby build` successfully now.
